# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vrenclouff/ClionProjects/NimServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vrenclouff/ClionProjects/NimServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vrenclouff/ClionProjects/NimServer/CMakeFiles /home/vrenclouff/ClionProjects/NimServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vrenclouff/ClionProjects/NimServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NimServer

# Build rule for target.
NimServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NimServer
.PHONY : NimServer

# fast build rule for target.
NimServer/fast:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/build
.PHONY : NimServer/fast

Application.o: Application.cpp.o
.PHONY : Application.o

# target to build an object file
Application.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Application.cpp.o
.PHONY : Application.cpp.o

Application.i: Application.cpp.i
.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s
.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Application.cpp.s
.PHONY : Application.cpp.s

Enums.o: Enums.cpp.o
.PHONY : Enums.o

# target to build an object file
Enums.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Enums.cpp.o
.PHONY : Enums.cpp.o

Enums.i: Enums.cpp.i
.PHONY : Enums.i

# target to preprocess a source file
Enums.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Enums.cpp.i
.PHONY : Enums.cpp.i

Enums.s: Enums.cpp.s
.PHONY : Enums.s

# target to generate assembly for a file
Enums.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Enums.cpp.s
.PHONY : Enums.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameManager.o: GameManager.cpp.o
.PHONY : GameManager.o

# target to build an object file
GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/GameManager.cpp.o
.PHONY : GameManager.cpp.o

GameManager.i: GameManager.cpp.i
.PHONY : GameManager.i

# target to preprocess a source file
GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/GameManager.cpp.i
.PHONY : GameManager.cpp.i

GameManager.s: GameManager.cpp.s
.PHONY : GameManager.s

# target to generate assembly for a file
GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/GameManager.cpp.s
.PHONY : GameManager.cpp.s

Logger.o: Logger.cpp.o
.PHONY : Logger.o

# target to build an object file
Logger.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Logger.cpp.o
.PHONY : Logger.cpp.o

Logger.i: Logger.cpp.i
.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s
.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

MainOptions.o: MainOptions.cpp.o
.PHONY : MainOptions.o

# target to build an object file
MainOptions.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/MainOptions.cpp.o
.PHONY : MainOptions.cpp.o

MainOptions.i: MainOptions.cpp.i
.PHONY : MainOptions.i

# target to preprocess a source file
MainOptions.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/MainOptions.cpp.i
.PHONY : MainOptions.cpp.i

MainOptions.s: MainOptions.cpp.s
.PHONY : MainOptions.s

# target to generate assembly for a file
MainOptions.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/MainOptions.cpp.s
.PHONY : MainOptions.cpp.s

Manager.o: Manager.cpp.o
.PHONY : Manager.o

# target to build an object file
Manager.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Manager.cpp.o
.PHONY : Manager.cpp.o

Manager.i: Manager.cpp.i
.PHONY : Manager.i

# target to preprocess a source file
Manager.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Manager.cpp.i
.PHONY : Manager.cpp.i

Manager.s: Manager.cpp.s
.PHONY : Manager.s

# target to generate assembly for a file
Manager.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Manager.cpp.s
.PHONY : Manager.cpp.s

NetworkService.o: NetworkService.cpp.o
.PHONY : NetworkService.o

# target to build an object file
NetworkService.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/NetworkService.cpp.o
.PHONY : NetworkService.cpp.o

NetworkService.i: NetworkService.cpp.i
.PHONY : NetworkService.i

# target to preprocess a source file
NetworkService.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/NetworkService.cpp.i
.PHONY : NetworkService.cpp.i

NetworkService.s: NetworkService.cpp.s
.PHONY : NetworkService.s

# target to generate assembly for a file
NetworkService.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/NetworkService.cpp.s
.PHONY : NetworkService.cpp.s

Parameters.o: Parameters.cpp.o
.PHONY : Parameters.o

# target to build an object file
Parameters.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Parameters.cpp.o
.PHONY : Parameters.cpp.o

Parameters.i: Parameters.cpp.i
.PHONY : Parameters.i

# target to preprocess a source file
Parameters.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Parameters.cpp.i
.PHONY : Parameters.cpp.i

Parameters.s: Parameters.cpp.s
.PHONY : Parameters.s

# target to generate assembly for a file
Parameters.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/Parameters.cpp.s
.PHONY : Parameters.cpp.s

RCVMessage.o: RCVMessage.cpp.o
.PHONY : RCVMessage.o

# target to build an object file
RCVMessage.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/RCVMessage.cpp.o
.PHONY : RCVMessage.cpp.o

RCVMessage.i: RCVMessage.cpp.i
.PHONY : RCVMessage.i

# target to preprocess a source file
RCVMessage.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/RCVMessage.cpp.i
.PHONY : RCVMessage.cpp.i

RCVMessage.s: RCVMessage.cpp.s
.PHONY : RCVMessage.s

# target to generate assembly for a file
RCVMessage.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/RCVMessage.cpp.s
.PHONY : RCVMessage.cpp.s

RouterService.o: RouterService.cpp.o
.PHONY : RouterService.o

# target to build an object file
RouterService.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/RouterService.cpp.o
.PHONY : RouterService.cpp.o

RouterService.i: RouterService.cpp.i
.PHONY : RouterService.i

# target to preprocess a source file
RouterService.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/RouterService.cpp.i
.PHONY : RouterService.cpp.i

RouterService.s: RouterService.cpp.s
.PHONY : RouterService.s

# target to generate assembly for a file
RouterService.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/RouterService.cpp.s
.PHONY : RouterService.cpp.s

SNDMessage.o: SNDMessage.cpp.o
.PHONY : SNDMessage.o

# target to build an object file
SNDMessage.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SNDMessage.cpp.o
.PHONY : SNDMessage.cpp.o

SNDMessage.i: SNDMessage.cpp.i
.PHONY : SNDMessage.i

# target to preprocess a source file
SNDMessage.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SNDMessage.cpp.i
.PHONY : SNDMessage.cpp.i

SNDMessage.s: SNDMessage.cpp.s
.PHONY : SNDMessage.s

# target to generate assembly for a file
SNDMessage.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SNDMessage.cpp.s
.PHONY : SNDMessage.cpp.s

SafeList.o: SafeList.cpp.o
.PHONY : SafeList.o

# target to build an object file
SafeList.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SafeList.cpp.o
.PHONY : SafeList.cpp.o

SafeList.i: SafeList.cpp.i
.PHONY : SafeList.i

# target to preprocess a source file
SafeList.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SafeList.cpp.i
.PHONY : SafeList.cpp.i

SafeList.s: SafeList.cpp.s
.PHONY : SafeList.s

# target to generate assembly for a file
SafeList.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SafeList.cpp.s
.PHONY : SafeList.cpp.s

SafeQueue.o: SafeQueue.cpp.o
.PHONY : SafeQueue.o

# target to build an object file
SafeQueue.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SafeQueue.cpp.o
.PHONY : SafeQueue.cpp.o

SafeQueue.i: SafeQueue.cpp.i
.PHONY : SafeQueue.i

# target to preprocess a source file
SafeQueue.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SafeQueue.cpp.i
.PHONY : SafeQueue.cpp.i

SafeQueue.s: SafeQueue.cpp.s
.PHONY : SafeQueue.s

# target to generate assembly for a file
SafeQueue.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SafeQueue.cpp.s
.PHONY : SafeQueue.cpp.s

SenderService.o: SenderService.cpp.o
.PHONY : SenderService.o

# target to build an object file
SenderService.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SenderService.cpp.o
.PHONY : SenderService.cpp.o

SenderService.i: SenderService.cpp.i
.PHONY : SenderService.i

# target to preprocess a source file
SenderService.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SenderService.cpp.i
.PHONY : SenderService.cpp.i

SenderService.s: SenderService.cpp.s
.PHONY : SenderService.s

# target to generate assembly for a file
SenderService.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/SenderService.cpp.s
.PHONY : SenderService.cpp.s

StringUtils.o: StringUtils.cpp.o
.PHONY : StringUtils.o

# target to build an object file
StringUtils.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/StringUtils.cpp.o
.PHONY : StringUtils.cpp.o

StringUtils.i: StringUtils.cpp.i
.PHONY : StringUtils.i

# target to preprocess a source file
StringUtils.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/StringUtils.cpp.i
.PHONY : StringUtils.cpp.i

StringUtils.s: StringUtils.cpp.s
.PHONY : StringUtils.s

# target to generate assembly for a file
StringUtils.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/StringUtils.cpp.s
.PHONY : StringUtils.cpp.s

User.o: User.cpp.o
.PHONY : User.o

# target to build an object file
User.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/User.cpp.o
.PHONY : User.cpp.o

User.i: User.cpp.i
.PHONY : User.i

# target to preprocess a source file
User.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/User.cpp.i
.PHONY : User.cpp.i

User.s: User.cpp.s
.PHONY : User.s

# target to generate assembly for a file
User.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/User.cpp.s
.PHONY : User.cpp.s

UserManager.o: UserManager.cpp.o
.PHONY : UserManager.o

# target to build an object file
UserManager.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/UserManager.cpp.o
.PHONY : UserManager.cpp.o

UserManager.i: UserManager.cpp.i
.PHONY : UserManager.i

# target to preprocess a source file
UserManager.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/UserManager.cpp.i
.PHONY : UserManager.cpp.i

UserManager.s: UserManager.cpp.s
.PHONY : UserManager.s

# target to generate assembly for a file
UserManager.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/UserManager.cpp.s
.PHONY : UserManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/NimServer.dir/build.make CMakeFiles/NimServer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... NimServer"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Application.o"
	@echo "... Application.i"
	@echo "... Application.s"
	@echo "... Enums.o"
	@echo "... Enums.i"
	@echo "... Enums.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameManager.o"
	@echo "... GameManager.i"
	@echo "... GameManager.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... MainOptions.o"
	@echo "... MainOptions.i"
	@echo "... MainOptions.s"
	@echo "... Manager.o"
	@echo "... Manager.i"
	@echo "... Manager.s"
	@echo "... NetworkService.o"
	@echo "... NetworkService.i"
	@echo "... NetworkService.s"
	@echo "... Parameters.o"
	@echo "... Parameters.i"
	@echo "... Parameters.s"
	@echo "... RCVMessage.o"
	@echo "... RCVMessage.i"
	@echo "... RCVMessage.s"
	@echo "... RouterService.o"
	@echo "... RouterService.i"
	@echo "... RouterService.s"
	@echo "... SNDMessage.o"
	@echo "... SNDMessage.i"
	@echo "... SNDMessage.s"
	@echo "... SafeList.o"
	@echo "... SafeList.i"
	@echo "... SafeList.s"
	@echo "... SafeQueue.o"
	@echo "... SafeQueue.i"
	@echo "... SafeQueue.s"
	@echo "... SenderService.o"
	@echo "... SenderService.i"
	@echo "... SenderService.s"
	@echo "... StringUtils.o"
	@echo "... StringUtils.i"
	@echo "... StringUtils.s"
	@echo "... User.o"
	@echo "... User.i"
	@echo "... User.s"
	@echo "... UserManager.o"
	@echo "... UserManager.i"
	@echo "... UserManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

